hand_description:
  arm:
    hand_frame: bhand_ftsensor
    robot_frame: base_link
    attached_objects_name: attached
    attach_link: bhand_link33
    hand_group_name: hand
    arm_group_name: arm
    hand_database_name: Barrett
    hand_joints: [bhand_j11_joint,bhand_j12_joint,bhand_j13_joint,bhand_j21_joint,bhand_j22_joint,bhand_j23_joint,bhand_j32_joint,bhand_j33_joint]
    hand_touch_links: [bhand_base,bhand_link11,bhand_link12,bhand_link13,bhand_link21,bhand_link22,bhand_link23,bhand_link32,bhand_link33]
    hand_fingertip_links: [bhand_link13,bhand_link23,bhand_link33]
    hand_approach_direction: [0.0,1.0,0.0]
    arm_joints: [wam_j1_joint,wam_j2_joint,wam_j3_joint,wam_j4_joint,wam_j5_joint,wam_j6_joint,wam_j7_joint]
