min_sensor_dist: .05
self_see_default_padding: .01
self_see_default_scale: 1.0
self_see_links:
  - name: wam_base
    padding: .04
  - name: j1
    padding: .04
  - name: j2
    padding: .04
  - name: j3
    padding: .04
  - name: j4
    padding: .04
  - name: j5
    padding: .04
  - name: j6
    padding: .04
  - name: j7
    padding: .04
  - name: bhand_ftsensor
    padding: .04
  - name: bhand_base
    padding: .04
  - name: bhand_link11
    padding: .04
  - name: bhand_link12
    padding: .04
  - name: bhand_link13
    padding: .04
  - name: bhand_link21
    padding: .04
  - name: bhand_link22
    padding: .04
  - name: bhand_link23
    padding: .04
  - name: bhand_link32
    padding: .04
  - name: bhand_link33
    padding: .04

