multi_dof_joints:
  - name: world_joint
    type: Fixed
    parent_frame_id: base_link
    child_frame_id: base_link
groups:
  - name: arm
    base_link: wam_base
    tip_link: bhand_ftsensor
  - name: hand
    joints:
      - bhand_base_joint
      - bhand_j11_joint
      - bhand_j12_joint
      - bhand_j13_joint
      - bhand_j21_joint
      - bhand_j22_joint
      - bhand_j23_joint
      - bhand_j32_joint
      - bhand_j33_joint
default_collision_operations:
  - object1: base_link
    object2: wam_base_kinect_link
    operation: disable  # Adjacent in collision
  -
    object1: wam_base_kinect_link
    object2: wam_base_kinect_depth_frame
    operation: disable  # Adjacent in collision
  -
    object1: wam_base_kinect_depth_frame
    object2: wam_base_kinect_depth_optical_frame
    operation: disable  # Adjacent in collision
  -
    object1: wam_base_kinect_link
    object2: wam_base_kinect_rgb_frame
    operation: disable  # Adjacent in collision
  -
    object1: wam_base_kinect_rgb_frame
    object2: wam_base_kinect_rgb_optical_frame
    operation: disable  # Adjacent in collision
  -
    object1: base_link
    object2: wam_base
    operation: disable  # Adjacent in collision
  -
    object1: wam_base
    object2: j1
    operation: disable  # Adjacent in collision
  -
    object1: j1
    object2: j2
    operation: disable  # Adjacent in collision
  -
    object1: j1
    object2: j3
    operation: disable  # Adjacent in collision
  -
    object1: j2
    object2: j3
    operation: disable  # Adjacent in collision
  -
    object1: j3
    object2: j4
    operation: disable  # Adjacent in collision
  -
    object1: j3
    object2: j5
    operation: disable  # Adjacent in collision
  -
    object1: j4
    object2: j5
    operation: disable  # Adjacent in collision
  -
    object1: j4
    object2: j6
    operation: disable  # Adjacent in collision
  -
    object1: j5
    object2: j6
    operation: disable  # Adjacent in collision
  -
    object1: j6
    object2: j7
    operation: disable  # Adjacent in collision
  -
    object1: j6
    object2: bhand_base
    operation: disable  # Adjacent in collision
  -
    object1: j7
    object2: bhand_ftsensor
    operation: disable  # Adjacent in collision
  -
    object1: j7
    object2: bhand_base
    operation: disable  # Adjacent in collision
  -
    object1: bhand_ftsensor
    object2: bhand_base
    operation: disable  # Adjacent in collision
  -
    object1: bhand_base
    object2: bhand_link11
    operation: disable  # Adjacent in collision
  -
    object1: bhand_link11
    object2: bhand_link12
    operation: disable  # Adjacent in collision
  -
    object1: bhand_link12
    object2: bhand_link13
    operation: disable  # Adjacent in collision
  -
    object1: bhand_link13
    object2: bhand_base
    operation: disable  # Adjacent in collision
  -
    object1: bhand_link13
    object2: bhand_link21
    operation: disable  # Adjacent in collision
  -
    object1: bhand_link13
    object2: bhand_link22
    operation: disable  # Adjacent in collision
  -
    object1: bhand_link13
    object2: bhand_link23
    operation: disable  # Adjacent in collision
  -
    object1: bhand_link13
    object2: bhand_link31
    operation: disable  # Adjacent in collision
  -
    object1: bhand_link13
    object2: bhand_link32
    operation: disable  # Adjacent in collision
  -
    object1: bhand_link13
    object2: bhand_link33
    operation: disable  # Adjacent in collision
  -
    object1: bhand_base
    object2: bhand_link21
    operation: disable  # Adjacent in collision
  -
    object1: bhand_link21
    object2: bhand_link22
    operation: disable  # Adjacent in collision
  -
    object1: bhand_link22
    object2: bhand_link23
    operation: disable  # Adjacent in collision
  -
    object1: bhand_link23
    object2: bhand_base
    operation: disable  # Adjacent in collision
  -
    object1: bhand_link23
    object2: bhand_link12
    operation: disable  # Adjacent in collision
  -
    object1: bhand_link23
    object2: bhand_base
    operation: disable  # Adjacent in collision
  -
    object1: bhand_link23
    object2: bhand_link31
    operation: disable  # Adjacent in collision
  -
    object1: bhand_link23
    object2: bhand_link32
    operation: disable  # Adjacent in collision
  -
    object1: bhand_link23
    object2: bhand_link33
    operation: disable  # Adjacent in collision
  -
    object1: bhand_base
    object2: bhand_link32
    operation: disable  # Adjacent in collision
  -
    object1: bhand_link32
    object2: bhand_link33
    operation: disable  # Adjacent in collision
  -
    object1: bhand_link33
    object2: bhand_base
    operation: disable  # Adjacent in collision
  -
    object1: bhand_link33
    object2: bhand_link12
    operation: disable  # Adjacent in collision
  -
    object1: bhand_link33
    object2: bhand_link21
    operation: disable  # Adjacent in collision
  -
    object1: bhand_link33
    object2: bhand_link22
    operation: disable  # Adjacent in collision
  -
    object1: bhand_base
    object2: j7
    operation: disable  # Always in collision
  -
    object1: wam_base_kinect_depth_optical_frame
    object2: wam_base_kinect_link
    operation: disable  # Always in collision
  -
    object1: wam_base_kinect_link
    object2: wam_base_kinect_rgb_optical_frame
    operation: disable  # Always in collision
  -
    object1: bhand_base
    object2: bhand_link12
    operation: disable  # Never in collision
  -
    object1: bhand_base
    object2: bhand_link22
    operation: disable  # Never in collision
  -
    object1: bhand_base
    object2: j2
    operation: disable  # Never in collision
  -
    object1: bhand_base
    object2: j4
    operation: disable  # Never in collision
  -
    object1: bhand_base
    object2: j5
    operation: disable  # Never in collision
  -
    object1: bhand_base
    object2: j6
    operation: disable  # Never in collision
  -
    object1: bhand_base
    object2: wam_base_kinect_depth_optical_frame
    operation: disable  # Never in collision
  -
    object1: bhand_base
    object2: wam_base_kinect_rgb_frame
    operation: disable  # Never in collision
  -
    object1: bhand_base
    object2: wam_base_kinect_rgb_optical_frame
    operation: disable  # Never in collision
  -
    object1: bhand_ftsensor
    object2: bhand_link11
    operation: disable  # Never in collision
  -
    object1: bhand_ftsensor
    object2: bhand_link12
    operation: disable  # Never in collision
  -
    object1: bhand_ftsensor
    object2: bhand_link13
    operation: disable  # Never in collision
  -
    object1: bhand_ftsensor
    object2: bhand_link21
    operation: disable  # Never in collision
  -
    object1: bhand_ftsensor
    object2: bhand_link22
    operation: disable  # Never in collision
  -
    object1: bhand_ftsensor
    object2: bhand_link23
    operation: disable  # Never in collision
  -
    object1: bhand_ftsensor
    object2: bhand_link32
    operation: disable  # Never in collision
  -
    object1: bhand_ftsensor
    object2: bhand_link33
    operation: disable  # Never in collision
  -
    object1: bhand_ftsensor
    object2: j2
    operation: disable  # Never in collision
  -
    object1: bhand_ftsensor
    object2: j4
    operation: disable  # Never in collision
  -
    object1: bhand_ftsensor
    object2: j5
    operation: disable  # Never in collision
  -
    object1: bhand_ftsensor
    object2: j6
    operation: disable  # Never in collision
  -
    object1: bhand_ftsensor
    object2: wam_base_kinect_depth_optical_frame
    operation: disable  # Never in collision
  -
    object1: bhand_ftsensor
    object2: wam_base_kinect_rgb_frame
    operation: disable  # Never in collision
  -
    object1: bhand_ftsensor
    object2: wam_base_kinect_rgb_optical_frame
    operation: disable  # Never in collision
  -
    object1: bhand_link11
    object2: bhand_link13
    operation: disable  # Never in collision
  -
    object1: bhand_link11
    object2: bhand_link21
    operation: disable  # Never in collision
  -
    object1: bhand_link11
    object2: bhand_link22
    operation: disable  # Never in collision
  -
    object1: bhand_link11
    object2: bhand_link23
    operation: disable  # Never in collision
  -
    object1: bhand_link11
    object2: bhand_link32
    operation: disable  # Never in collision
  -
    object1: bhand_link11
    object2: bhand_link33
    operation: disable  # Never in collision
  -
    object1: bhand_link11
    object2: j2
    operation: disable  # Never in collision
  -
    object1: bhand_link11
    object2: j4
    operation: disable  # Never in collision
  -
    object1: bhand_link11
    object2: j5
    operation: disable  # Never in collision
  -
    object1: bhand_link11
    object2: j6
    operation: disable  # Never in collision
  -
    object1: bhand_link11
    object2: j7
    operation: disable  # Never in collision
  -
    object1: bhand_link11
    object2: wam_base_kinect_depth_optical_frame
    operation: disable  # Never in collision
  -
    object1: bhand_link12
    object2: bhand_link21
    operation: disable  # Never in collision
  -
    object1: bhand_link12
    object2: bhand_link22
    operation: disable  # Never in collision
  -
    object1: bhand_link12
    object2: bhand_link32
    operation: disable  # Never in collision
  -
    object1: bhand_link12
    object2: bhand_link33
    operation: disable  # Never in collision
  -
    object1: bhand_link12
    object2: j4
    operation: disable  # Never in collision
  -
    object1: bhand_link12
    object2: j5
    operation: disable  # Never in collision
  -
    object1: bhand_link12
    object2: j6
    operation: disable  # Never in collision
  -
    object1: bhand_link12
    object2: j7
    operation: disable  # Never in collision
  -
    object1: bhand_link12
    object2: wam_base_kinect_depth_optical_frame
    operation: disable  # Never in collision
  -
    object1: bhand_link12
    object2: wam_base_kinect_rgb_frame
    operation: disable  # Never in collision
  -
    object1: bhand_link12
    object2: wam_base_kinect_rgb_optical_frame
    operation: disable  # Never in collision
  -
    object1: bhand_link13
    object2: bhand_link21
    operation: disable  # Never in collision
  -
    object1: bhand_link13
    object2: j4
    operation: disable  # Never in collision
  -
    object1: bhand_link13
    object2: j5
    operation: disable  # Never in collision
  -
    object1: bhand_link13
    object2: j6
    operation: disable  # Never in collision
  -
    object1: bhand_link13
    object2: j7
    operation: disable  # Never in collision
  -
    object1: bhand_link13
    object2: wam_base_kinect_depth_optical_frame
    operation: disable  # Never in collision
  -
    object1: bhand_link13
    object2: wam_base_kinect_rgb_frame
    operation: disable  # Never in collision
  -
    object1: bhand_link13
    object2: wam_base_kinect_rgb_optical_frame
    operation: disable  # Never in collision
  -
    object1: bhand_link21
    object2: bhand_link23
    operation: disable  # Never in collision
  -
    object1: bhand_link21
    object2: bhand_link32
    operation: disable  # Never in collision
  -
    object1: bhand_link21
    object2: bhand_link33
    operation: disable  # Never in collision
  -
    object1: bhand_link21
    object2: j2
    operation: disable  # Never in collision
  -
    object1: bhand_link21
    object2: j4
    operation: disable  # Never in collision
  -
    object1: bhand_link21
    object2: j5
    operation: disable  # Never in collision
  -
    object1: bhand_link21
    object2: j6
    operation: disable  # Never in collision
  -
    object1: bhand_link21
    object2: j7
    operation: disable  # Never in collision
  -
    object1: bhand_link21
    object2: wam_base_kinect_depth_optical_frame
    operation: disable  # Never in collision
  -
    object1: bhand_link21
    object2: wam_base_kinect_rgb_frame
    operation: disable  # Never in collision
  -
    object1: bhand_link21
    object2: wam_base_kinect_rgb_optical_frame
    operation: disable  # Never in collision
  -
    object1: bhand_link22
    object2: bhand_link32
    operation: disable  # Never in collision
  -
    object1: bhand_link22
    object2: bhand_link33
    operation: disable  # Never in collision
  -
    object1: bhand_link22
    object2: j4
    operation: disable  # Never in collision
  -
    object1: bhand_link22
    object2: j5
    operation: disable  # Never in collision
  -
    object1: bhand_link22
    object2: j6
    operation: disable  # Never in collision
  -
    object1: bhand_link22
    object2: j7
    operation: disable  # Never in collision
  -
    object1: bhand_link22
    object2: wam_base_kinect_depth_optical_frame
    operation: disable  # Never in collision
  -
    object1: bhand_link22
    object2: wam_base_kinect_rgb_frame
    operation: disable  # Never in collision
  -
    object1: bhand_link22
    object2: wam_base_kinect_rgb_optical_frame
    operation: disable  # Never in collision
  -
    object1: bhand_link23
    object2: j4
    operation: disable  # Never in collision
  -
    object1: bhand_link23
    object2: j5
    operation: disable  # Never in collision
  -
    object1: bhand_link23
    object2: j6
    operation: disable  # Never in collision
  -
    object1: bhand_link23
    object2: j7
    operation: disable  # Never in collision
  -
    object1: bhand_link23
    object2: wam_base_kinect_depth_optical_frame
    operation: disable  # Never in collision
  -
    object1: bhand_link23
    object2: wam_base_kinect_rgb_frame
    operation: disable  # Never in collision
  -
    object1: bhand_link23
    object2: wam_base_kinect_rgb_optical_frame
    operation: disable  # Never in collision
  -
    object1: bhand_link32
    object2: j4
    operation: disable  # Never in collision
  -
    object1: bhand_link32
    object2: j5
    operation: disable  # Never in collision
  -
    object1: bhand_link32
    object2: j6
    operation: disable  # Never in collision
  -
    object1: bhand_link32
    object2: j7
    operation: disable  # Never in collision
  -
    object1: bhand_link32
    object2: wam_base_kinect_depth_optical_frame
    operation: disable  # Never in collision
  -
    object1: bhand_link32
    object2: wam_base_kinect_rgb_frame
    operation: disable  # Never in collision
  -
    object1: bhand_link32
    object2: wam_base_kinect_rgb_optical_frame
    operation: disable  # Never in collision
  -
    object1: bhand_link33
    object2: j4
    operation: disable  # Never in collision
  -
    object1: bhand_link33
    object2: j5
    operation: disable  # Never in collision
  -
    object1: bhand_link33
    object2: j6
    operation: disable  # Never in collision
  -
    object1: bhand_link33
    object2: j7
    operation: disable  # Never in collision
  -
    object1: bhand_link33
    object2: wam_base_kinect_depth_optical_frame
    operation: disable  # Never in collision
  -
    object1: bhand_link33
    object2: wam_base_kinect_rgb_frame
    operation: disable  # Never in collision
  -
    object1: bhand_link33
    object2: wam_base_kinect_rgb_optical_frame
    operation: disable  # Never in collision
  -
    object1: j1
    object2: j3
    operation: disable  # Never in collision
  -
    object1: j1
    object2: j4
    operation: disable  # Never in collision
  -
    object1: j1
    object2: j5
    operation: disable  # Never in collision
  -
    object1: j1
    object2: wam_base_kinect_depth_optical_frame
    operation: disable  # Never in collision
  -
    object1: j1
    object2: wam_base_kinect_link
    operation: disable  # Never in collision
  -
    object1: j1
    object2: wam_base_kinect_rgb_frame
    operation: disable  # Never in collision
  -
    object1: j1
    object2: wam_base_kinect_rgb_optical_frame
    operation: disable  # Never in collision
  -
    object1: j2
    object2: j4
    operation: disable  # Never in collision
  -
    object1: j2
    object2: j5
    operation: disable  # Never in collision
  -
    object1: j2
    object2: j6
    operation: disable  # Never in collision
  -
    object1: j2
    object2: j7
    operation: disable  # Never in collision
  -
    object1: j2
    object2: wam_base
    operation: disable  # Never in collision
  -
    object1: j2
    object2: wam_base_kinect_depth_optical_frame
    operation: disable  # Never in collision
  -
    object1: j2
    object2: wam_base_kinect_link
    operation: disable  # Never in collision
  -
    object1: j2
    object2: wam_base_kinect_rgb_frame
    operation: disable  # Never in collision
  -
    object1: j2
    object2: wam_base_kinect_rgb_optical_frame
    operation: disable  # Never in collision
  -
    object1: j3
    object2: j5
    operation: disable  # Never in collision
  -
    object1: j3
    object2: wam_base
    operation: disable  # Never in collision
  -
    object1: j3
    object2: wam_base_kinect_depth_optical_frame
    operation: disable  # Never in collision
  -
    object1: j3
    object2: wam_base_kinect_link
    operation: disable  # Never in collision
  -
    object1: j3
    object2: wam_base_kinect_rgb_frame
    operation: disable  # Never in collision
  -
    object1: j3
    object2: wam_base_kinect_rgb_optical_frame
    operation: disable  # Never in collision
  -
    object1: j4
    object2: j7
    operation: disable  # Never in collision
  -
    object1: j4
    object2: wam_base_kinect_depth_optical_frame
    operation: disable  # Never in collision
  -
    object1: j4
    object2: wam_base_kinect_link
    operation: disable  # Never in collision
  -
    object1: j4
    object2: wam_base_kinect_rgb_frame
    operation: disable  # Never in collision
  -
    object1: j4
    object2: wam_base_kinect_rgb_optical_frame
    operation: disable  # Never in collision
  -
    object1: j5
    object2: j7
    operation: disable  # Never in collision
  -
    object1: j5
    object2: wam_base_kinect_depth_optical_frame
    operation: disable  # Never in collision
  -
    object1: j5
    object2: wam_base_kinect_link
    operation: disable  # Never in collision
  -
    object1: j5
    object2: wam_base_kinect_rgb_frame
    operation: disable  # Never in collision
  -
    object1: j5
    object2: wam_base_kinect_rgb_optical_frame
    operation: disable  # Never in collision
  -
    object1: j6
    object2: wam_base_kinect_depth_optical_frame
    operation: disable  # Never in collision
  -
    object1: j6
    object2: wam_base_kinect_link
    operation: disable  # Never in collision
  -
    object1: j6
    object2: wam_base_kinect_rgb_frame
    operation: disable  # Never in collision
  -
    object1: j6
    object2: wam_base_kinect_rgb_optical_frame
    operation: disable  # Never in collision
  -
    object1: j7
    object2: wam_base_kinect_depth_optical_frame
    operation: disable  # Never in collision
  -
    object1: j7
    object2: wam_base_kinect_link
    operation: disable  # Never in collision
  -
    object1: j7
    object2: wam_base_kinect_rgb_frame
    operation: disable  # Never in collision
  -
    object1: j7
    object2: wam_base_kinect_rgb_optical_frame
    operation: disable  # Never in collision
  -
    object1: wam_base
    object2: wam_base_kinect_depth_optical_frame
    operation: disable  # Never in collision
  -
    object1: wam_base
    object2: wam_base_kinect_link
    operation: disable  # Never in collision
  -
    object1: wam_base
    object2: wam_base_kinect_rgb_frame
    operation: disable  # Never in collision
  -
    object1: wam_base
    object2: wam_base_kinect_rgb_optical_frame
    operation: disable  # Never in collision
  -
    object1: wam_base_kinect_depth_optical_frame
    object2: wam_base_kinect_rgb_frame
    operation: disable  # Never in collision
  -
    object1: wam_base_kinect_depth_optical_frame
    object2: wam_base_kinect_rgb_optical_frame
    operation: disable  # Never in collision
