joint_limits:
  wam_j1_joint:
    has_position_limits: true
    has_velocity_limits: true
    max_velocity: 0.75
    has_acceleration_limits: true
    max_acceleration: 1
    angle_wraparound: false
  wam_j2_joint:
    has_position_limits: true
    has_velocity_limits: true
    max_velocity: 0.75
    has_acceleration_limits: true
    max_acceleration: 1
    angle_wraparound: false
  wam_j3_joint:
    has_position_limits: true
    has_velocity_limits: true
    max_velocity: 0.75
    has_acceleration_limits: true
    max_acceleration: 1
    angle_wraparound: false
  wam_j4_joint:
    has_position_limits: true
    has_velocity_limits: true
    max_velocity: 0.75
    has_acceleration_limits: true
    max_acceleration: 1
    angle_wraparound: false
  wam_j5_joint:
    has_position_limits: true
    has_velocity_limits: true
    max_velocity: 0.75
    has_acceleration_limits: true
    max_acceleration: 1
    angle_wraparound: false
  wam_j6_joint:
    has_position_limits: true
    has_velocity_limits: true
    max_velocity: 0.75
    has_acceleration_limits: true
    max_acceleration: 1
    angle_wraparound: false
  wam_j7_joint:
    has_position_limits: true
    has_velocity_limits: true
    max_velocity: 0.75
    has_acceleration_limits: true
    max_acceleration: 1
    angle_wraparound: false
  bhand_j11_joint:
    has_position_limits: true
    has_velocity_limits: true
    max_velocity: 0.75
    has_acceleration_limits: true
    max_acceleration: 1
    angle_wraparound: false
  bhand_j12_joint:
    has_position_limits: true
    has_velocity_limits: true
    max_velocity: 0.75
    has_acceleration_limits: true
    max_acceleration: 1
    angle_wraparound: false
  bhand_j13_joint:
    has_position_limits: true
    has_velocity_limits: true
    max_velocity: 0.75
    has_acceleration_limits: true
    max_acceleration: 1
    angle_wraparound: false
  bhand_j21_joint:
    has_position_limits: true
    has_velocity_limits: true
    max_velocity: 0.75
    has_acceleration_limits: true
    max_acceleration: 1
    angle_wraparound: false
  bhand_j22_joint:
    has_position_limits: true
    has_velocity_limits: true
    max_velocity: 0.75
    has_acceleration_limits: true
    max_acceleration: 1
    angle_wraparound: false
  bhand_j23_joint:
    has_position_limits: true
    has_velocity_limits: true
    max_velocity: 0.75
    has_acceleration_limits: true
    max_acceleration: 1
    angle_wraparound: false
  bhand_j32_joint:
    has_position_limits: true
    has_velocity_limits: true
    max_velocity: 0.75
    has_acceleration_limits: true
    max_acceleration: 1
    angle_wraparound: false
  bhand_j33_joint:
    has_position_limits: true
    has_velocity_limits: true
    max_velocity: 0.75
    has_acceleration_limits: true
    max_acceleration: 1
    angle_wraparound: false
